/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_unipr_netsec_tuntap_TunSocket */

#ifndef _Included_it_unipr_netsec_tuntap_TunSocket
#define _Included_it_unipr_netsec_tuntap_TunSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_unipr_netsec_tuntap_TunSocket
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_unipr_netsec_tuntap_TunSocket_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_unipr_netsec_tuntap_TunSocket
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_it_unipr_netsec_tuntap_TunSocket_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     it_unipr_netsec_tuntap_TunSocket
 * Method:    read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_it_unipr_netsec_tuntap_TunSocket_read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
